-- Add 5 new simple creative types: ADTEXT, VIDEO, THUMBNAIL, HEADLINE, DESCRIPTION
ALTER TYPE "creative_type" ADD VALUE IF NOT EXISTS 'ADTEXT';
ALTER TYPE "creative_type" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "creative_type" ADD VALUE IF NOT EXISTS 'THUMBNAIL';
ALTER TYPE "creative_type" ADD VALUE IF NOT EXISTS 'HEADLINE';
ALTER TYPE "creative_type" ADD VALUE IF NOT EXISTS 'DESCRIPTION';
